version: "3.9"

services:
  backend:
    container_name: media-service-util
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - main-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

networks:
  main-network:
    driver: bridge
